spring:
  datasource:
    druid:
      url: jdbc:mysql://172.16.1.20:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: yooli.net@127
      max-active: 30
      max-wait: 6000
      min-idle: 10
  redis:
    host: 172.16.2.126
    port: 7874
    password: TDOX1eI5
    database: 0
  pool:
    max-active: 100
    max-wait: -1
    max-idle: 20
    min-idle: 10
